// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/waiter": {
    params: {};
  };
  "/waiter/orders": {
    params: {};
  };
  "/chef": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/insights": {
    params: {};
  };
  "/admin/menu": {
    params: {};
  };
  "/admin/orders": {
    params: {};
  };
  "/admin/addOrder": {
    params: {};
  };
  "/admin/users": {
    params: {};
  };
  "/chef/menu": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/waiter" | "/waiter/orders" | "/chef" | "/admin" | "/admin/insights" | "/admin/menu" | "/admin/orders" | "/admin/addOrder" | "/admin/users" | "/chef/menu";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/waiter/menu.tsx": {
    id: "routes/waiter/menu";
    page: "/waiter";
  };
  "routes/waiter/Orders.tsx": {
    id: "routes/waiter/Orders";
    page: "/waiter/orders";
  };
  "routes/chef/index.tsx": {
    id: "routes/chef/index";
    page: "/chef";
  };
  "routes/admin/index.tsx": {
    id: "routes/admin/index";
    page: "/admin";
  };
  "routes/admin/insights.tsx": {
    id: "routes/admin/insights";
    page: "/admin/insights";
  };
  "routes/admin/menu.tsx": {
    id: "routes/admin/menu";
    page: "/admin/menu";
  };
  "routes/admin/orders.tsx": {
    id: "routes/admin/orders";
    page: "/admin/orders";
  };
  "routes/admin/addOrder.tsx": {
    id: "routes/admin/addOrder";
    page: "/admin/addOrder";
  };
  "routes/admin/users.tsx": {
    id: "routes/admin/users";
    page: "/admin/users";
  };
  "routes/chef/menu.tsx": {
    id: "routes/chef/menu";
    page: "/chef/menu";
  };
};